# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push: 
     branches:
       - main
       
     paths:
       - 'school-cms/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: school-cms 
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: enabble docker advanced feature
        uses: docker/setup-buildx-action@v3

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: ./school-cms
          file: ./school-cms/Dockerfile
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test:V3.0.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
        

    

  
